//This file is generated by XKit.

enum ANIM_OF_OBJS {

	OBJS_ANIM_OK = 0 ,
	OBJS_ANIM_OK_PRESS = 1 ,
	OBJS_ANIM_PLAY = 2 ,
	OBJS_ANIM_PLAY_PRESS = 3 ,
	OBJS_ANIM_EGG = 4 ,
};

enum FRAME_OF_OBJS {

};

enum MODULE_OF_OBJS {

};

