//This file is generated by XKit.

enum ANIM_OF_UI {

	UI_ANIM_PLAY_BTN = 0 ,
	UI_ANIM_PLAY_BTN_DOWN = 1 ,
	UI_ANIM_PAUSE_BTN = 2 ,
	UI_ANIM_PAUSE_BTN_DOWN = 3 ,
	UI_ANIM_RETRY = 4 ,
	UI_ANIM_RETRY_DOWN = 5 ,
};

enum FRAME_OF_UI {

};

enum MODULE_OF_UI {

};

