//auto-generated by UIDefs.py

//-----layer interface-----
static const int UIID_INTERFACE_PAUSE = 0;
static const int UIID_INTERFACE_RETRY = 1;
static const int UIID_INTERFACE_FULLSCREENZONE = 2;


//-----layer main menu-----
static const int UIID_MAIN_MENU_PLAY_BUTTON = 0;


