//This file is generated by XKit.

enum ANIM_OF_BIRDS {

	BIRDS_ANIM_OK = 0 ,
	BIRDS_ANIM_OK_PRESS = 1 ,
	BIRDS_ANIM_PLAY = 2 ,
	BIRDS_ANIM_PLAY_PRESS = 3 ,
	BIRDS_ANIM_EGG = 4 ,
};

enum FRAME_OF_BIRDS {

};

enum MODULE_OF_BIRDS {

};

