//This file is generated by XKit.

enum ANIM_OF_FT {

	FT_ANIM_TEST = 0 ,
	FT_ANIM_TEST_CLONE = 1 ,
	FT_ANIM_BT = 2 ,
	FT_ANIM_BT_P = 3 ,
	FT_ANIM_BG0 = 4 ,
};

enum FRAME_OF_FT {

	FT_FRAME_F1 = 1 ,
	FT_FRAME_F2 = 2 ,
	FT_FRAME_RING = 3 ,
};

enum MODULE_OF_FT {

	FT_MODULE_RIGHT_HAND = 9 ,
	FT_MODULE_MONEY = 12 ,
};

