# UIDefs.py: read ui.xml and export UI defs

import sys, os
import xml.dom.minidom as minidom
import glob

class UIObject:
	def __init__(self):
		self.name=""
		
class UILayer:
	def __init__(self):
		self.name=""
		self.objs=[]
		
class ResXML:
	def __init__(self):
		self.layers = []
		
	def loadFromXML(self, xmlFilePath):		
		try:
			doc = minidom.parse(xmlFilePath)
			root = doc.documentElement
			layerNodes = root.getElementsByTagName('UILayer')
			for layerNode in layerNodes:
				layer = UILayer()
				layer.name = layerNode.getAttribute('name')
				objsNode = layerNode.getElementsByTagName("UIObjects")
				if len(objsNode)>0:
					objNodes = objsNode[0].getElementsByTagName('UIObject')
					for objNode in objNodes:
						obj = UIObject()
						obj.name = objNode.getAttribute('name')
						layer.objs.append(obj)
						
				self.layers.append(layer)			
		except:
			print "error: can not load xml file %s" %(xmlFilePath)
			
	def writeToDefsFile(self, file):		
		if file:			
			for layer in self.layers:
				file.writelines("//-----layer "+layer.name+"-----\n")
				layer_name = layer.name.strip().replace(' ','_').upper()
				index = 0
				for obj in layer.objs:
					def_name = 'UIID_'+layer_name+'_'+obj.name.strip().replace(' ','_').upper()   
					file.writelines("static const int "+def_name+" = "+str(index)+";\n")
					index = index+1
				file.writelines("\n\n")
						
	def writeToDefs(self, defFilePath):		
		try:
			f = open(defFilePath, 'w')
			self.writeToDefsFile(f)
			f.close()
		except:
			print "error: can not write def file %s" %(defFilePath)
			
#############################################################################
			
def getFiles(dirPath, strMatch):
	if os.path.isdir(dirPath)==False:
		return None
	#files = os.listdir(dirPath)
	files = glob.glob(os.path.join(dirPath,strMatch))
	return files
	
        
if __name__=="__main__":        
    argc = len(sys.argv)
    if argc!=4:
        print 'Usage: UIDefs.py -f xmlFilePath defsFilePath'
        print 'or UIDefs.py -d dirPath defsFilePath'
    else:
		if  sys.argv[1]=='-f':
			res_xml = ResXML()
			res_xml.loadFromXML(sys.argv[2])
			res_xml.writeToDefs(sys.argv[3])  
		elif sys.argv[1]=='-d':
			files = getFiles(sys.argv[2], '*.xml')	
			print files
			defFilePath=sys.argv[3]
			if files!=None and len(files)>0:
				try:
					defFile = open(defFilePath, 'w')
					defFile.writelines("//auto-generated by UIDefs.py\n\n")
					for file in files:
						res_xml = ResXML()	
						res_xml.loadFromXML(file)
						res_xml.writeToDefsFile(defFile)
					defFile.close()
				except:
					print "error: can not write def file %s" %(defFilePath)					
		
		print 'UIDefs.py DONE! Output: %s' %(sys.argv[3]) 
